usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('lista/', views.UsuarioList.as_view(), name='lista_usuario'),
    path('lista-pdf/', views.UsuarioListPdf.as_view(), name='lista_pdf_usuario'),
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo_usuario'),
    path('municipios/', views.obtiene_municipios, name='obtiene_municipios'),
    path('activar/<slug:uid64>/<slug:token>', views.ActivarCuenta.as_view(), name='activar_cuenta'),
    path('eliminar/<int:pk>', views.UsuarioEliminar.as_view(), name='eliminar_usuario'),
    path('editar/<int:pk>', views.UsuarioActualizar.as_view(), name='editar_usuario'),
    path('detalles/<int:pk>', views.UsuarioDetalle.as_view(), name='detalles_usuario'),
    path('login/', views.UsuarioLogin.as_view(), name='login_usuario'),
    path('registro/', views.UsuarioRegistro.as_view(), name='registro_usuario'),
    path('dar-usuario/<int:pk>', views.UsuarioDarUsuario, name='dar_usuario_usuario'),
    path('dar-administrador/<int:pk>', views.UsuarioDarAdministrador, name='dar_administrador_usuario'),
    path('modificar-grupo/<int:user_id>/<int:grupo_id>/<int:opcion>', views.UsuarioModificarGrupo, name='modificar_grupo_usuario'),
    path("logout/", LogoutView.as_view(), name="logout"),
]

videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from videojuego.views import VideojuegoViewSet, CategoriaViewSet

router = routers.DefaultRouter()
router.register(r'videojuegos-api', VideojuegoViewSet)
router.register(r'categorias-api', CategoriaViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videojuegos/', include('videojuego.urls_videojuego')),
    path('categorias/', include('videojuego.urls_categoria')),
    path('usuarios/', include('usuarios.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User

# Create your models here.

class Usuario(User):
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado", on_delete=models.CASCADE)
    municipio = models.ForeignKey("usuarios.Municipio", verbose_name="Municipio", on_delete=models.CASCADE)
    foto = models.ImageField("Foto de perfil", upload_to='perfiles', blank=True, null=True)
    
    class Meta:
        permissions = [('permiso_usuario','usuario')]


class Estado(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Municipio(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado", on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    

usuarios/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Usuario

        fields = ('first_name','username','password','email','estado','municipio','foto')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Contraseña'}),
            'estado':forms.Select(attrs={'class':'form-control'}),
            'municipio':forms.Select(attrs={'class':'form-control'}),
            'foto':forms.FileInput(attrs={'class':'form-control'})
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class UsuarioActualizarForm(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('first_name','username','email','estado','municipio','foto')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'estado':forms.Select(attrs={'class':'form-control'}),
            'municipio':forms.Select(attrs={'class':'form-control'}),
            'foto':forms.FileInput(attrs={'class':'form-control'})
        }

class UsuarioRegistroForm(forms.ModelForm):

    class Meta:
        model = Usuario
        
        fields = ('username','password','email','estado','municipio')

        widgets = {
            'estado':forms.Select(attrs={'class':'form-control'}),
            'municipio':forms.Select(attrs={'class':'form-control'}),
        }

    def save(self, commit=True):
        user = super(UsuarioRegistroForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuarios/views.py
import functools

from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from .token import token_activacion
from django.views.generic import ListView
from .models import Usuario, Estado, Municipio
from .forms import UsuarioForm, UsuarioRegistroForm, UsuarioActualizarForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.mail import EmailMessage
from django.views.generic import TemplateView
from django.contrib import messages
from django_weasyprint import WeasyTemplateResponseMixin
from django_weasyprint.views import CONTENT_TYPE_PNG, WeasyTemplateResponse
from django.conf import settings
from django.contrib.auth.models import Group
from django import template

class NuevoUsuario(CreateView):
    model = Usuario
    form_class = UsuarioForm
    extra_context = {'etiqueta':'Nuevo','boton':'Agregar'}
    success_url = reverse_lazy('usuarios:lista_usuario')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.save()
        grupo = Group.objects.get(name='usuario') 
        user.groups.add(grupo)
        return super().form_valid(form)

class UsuarioRegistro(CreateView):
    template_name = 'signup.html'
    model = Usuario
    form_class = UsuarioRegistroForm
    success_url = reverse_lazy('usuarios:login_usuario')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        grupo = Group.objects.get(name='usuario') 
        user.groups.add(grupo)

        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        mensaje = render_to_string('confirmar_cuenta.html',
            {
                'usuario': user,
                'dominio': dominio,
                'uid': uid,
                'token': token
            }
        )
        asunto = 'Activa Cuenta Videojuegos'
        to = user.email
        email = EmailMessage(
            asunto,
            mensaje,
            to = [to]
        )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)

class ActivarCuenta(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uid64'])
            token = kwargs['token']
            user = Usuario.objects.get(id=uid)
        except:
            user = None
        
        if user and token_activacion.check_token(user,token):
            user.is_active = True
            user.save()
            messages.success(self.request, 'Cuenta activada con éxito.')
        else:
            messages.error(self.request, 'Token invalido, contacta al administrador')
        
        return redirect('usuarios:login_usuario')

def obtiene_municipios(request):
    if request.method == 'GET':
        return JsonResponse({'error':'Peticion incorrecta'}, safe=False, status=403)
    id_estado = request.POST.get('id')
    municipios = Municipio.objects.filter(estado_id=id_estado)

    json = []
    if not municipios:
        json.append({'error':'No se encontraron municipios para ese estado'})
    
    for municipio in municipios:
        json.append({'id':municipio.id, 'nombre':municipio.nombre})

    return JsonResponse(json, safe=False)

class UsuarioList(ListView):
    model = Usuario
    # usuario = Group.objects.get(name='usuario')
    # administrador = Group.objects.get(name='administrador')
    grupos = Group.objects.all()
    # extra_context = {'usuario_grupo':usuario, 'admin_grupo':administrador}
    extra_context = {'grupos':grupos}

class UsuarioEliminar(DeleteView):
    model = Usuario
    success_url = reverse_lazy('usuarios:lista_usuario')

class UsuarioActualizar(UpdateView):
    model = Usuario
    form_class = UsuarioActualizarForm
    extra_context = {'etiqueta':'Editar','boton':'Guardar'}
    success_url = reverse_lazy('usuarios:lista_usuario')

class UsuarioDetalle(DetailView):
    model = Usuario

class UsuarioLogin(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    
    def get_success_url(self):
        self.request.session['cuantos'] = 0
        self.request.session['total'] = 0.0
        self.request.session['videojuegos'] = {}
        return super().get_success_url()

def UsuarioDarUsuario(request,pk):
    usuario = Usuario.objects.get(id=pk)
    grupo = Group.objects.get(name='usuario') 
    usuario.groups.add(grupo)
    return redirect('usuarios:lista_usuario')

def UsuarioDarAdministrador(request,pk):
    usuario = Usuario.objects.get(id=pk)
    grupo = Group.objects.get(name='administrador') 
    usuario.groups.add(grupo)
    return redirect('usuarios:lista_usuario')

def UsuarioModificarGrupo(request, user_id, grupo_id, opcion):
    grupo = Group.objects.get(id=grupo_id)
    usuario = Usuario.objects.get(id=user_id)
    if opcion == 0:
        if grupo not in usuario.groups.all():
            messages.error(request, f'El usuario {usuario.username} no pertenece al grupo {grupo.name}.')
        else:
            if usuario.groups.count() <= 1:
                messages.error(request, f'El usuario {usuario.username} no puede quedar sin un grupo.')
            else:
                usuario.groups.remove(grupo)
                messages.success(request, f'El usuario {usuario.username} ya no pertenece al grupo {grupo.name}.')
    elif opcion == 1:
        if grupo in usuario.groups.all():
            messages.error(request, f'El usuario {usuario.username} ya pertenece al grupo {grupo.name}.')
        else:
            usuario.groups.add(grupo)
            messages.success(request, f'El usuario {usuario.username} pertenece al grupo {grupo.name}.')

    return redirect('usuarios:lista_usuario')

class VistaPdf(ListView):
    model = Usuario
    template_name = 'usuarios/usuario_pdf.html'

class UsuarioListPdf(WeasyTemplateResponseMixin, VistaPdf):
    # output of MyModelView rendered as PDF with hardcoded CSS
    pdf_stylesheets = [
        settings.STATICFILES_DIRS[0] + '/css/portal.css',
        settings.STATICFILES_DIRS[0] + '/css/estilos.css',
    ]
    # show pdf in-line (default: True, show download dialog)
    pdf_attachment = False
    # custom response class to configure url-fetcher
    pdf_name = 'foo.pdf'

usuarios/templates/base_log_sign.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>

    {% block titulo %}
      
    {% endblock titulo %}
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
    <link rel="shortcut icon" href="{% static 'images/favicon_48.png' %}">
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">

</head>

<body class="app app-login p-0">

{% block contenido %}

  
{% endblock contenido %}
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->

	<!-- JQuery -->
	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script> 
	{% block js %}
	
	{% endblock js %}

</body>
	
</html> 

usuarios/templates/confirmar_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Cuenta</title>
</head>
<body>
    <div>
        <h3>Validar cuenta</h3>
        <p>Hola {{usuario.username}}</p>
        <p>Para completar tu registro en el sistema de <b>Videojuegos</b> debes de dar click en el siguiente enlace.</p>
        <br>
        <hr>
        <p>
            <a href="http://{{dominio}}{% url 'usuarios:activar_cuenta' uid64=uid token=token %}">
                Activar cuenta
            </a>
        </p>
        <br>
        <hr>
        <p>Saludos.</p>
    </div>
    
</body>
</html>

usuarios/templates/login.html
{% extends "base_log_sign.html" %}
{% load static %}

{% block titulo %}
<title>Login Videojuegos</title>
{% endblock titulo %}

{% block contenido %}
{% if form.errors %}
<div class="alert alert-warning">
	<p>Usuario no encontrado</p>
</div>
{% endif %}  


{% if messages %}
	{% for message in messages %}
	  <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
		  {{message}}
	  </div>
	{% endfor %}
{% endif %}
	

<div class="row g-0 app-auth-wrapper">
<div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
	<div class="d-flex flex-column align-content-end">
		<div class="app-auth-body mx-auto">	
			<div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon mr-2" src="{% static 'images/app-logo.svg' %}" alt="logo"></a></div>
			<h2 class="auth-heading text-center mb-5">Log in to Portal</h2>
			<div class="auth-form-container text-left">
				<form class="auth-form login-form" method="POST">    
					{% csrf_token %}     
					<div class="email mb-3">
						<label class="sr-only" for="signin-email">Usuario</label>
						<input id="id_usernmae" name="username" type="text" class="form-control signin-email" placeholder="Nombre de Usuario" required="required">
					</div><!--//form-group-->
					<div class="password mb-3">
						<label class="sr-only" for="signin-password">Contraseña</label>
						<input id="id_password" name="password" type="password" class="form-control signin-password" placeholder="Contraseña" required="required">
						<div class="extra mt-3 row justify-content-between">
							<div class="col-6">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
									<label class="form-check-label" for="RememberPassword">
									Recordar
									</label>
								</div>
							</div><!--//col-6-->
							<div class="col-6">
								<div class="forgot-password text-right">
									<a href="reset-password.html">¿Olvide contraseña?</a>
								</div>
							</div><!--//col-6-->
						</div><!--//extra-->
					</div><!--//form-group-->
					<div class="text-center">
						<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">Log In</button>
					</div>
				</form>
				
				<div class="auth-option text-center pt-5">No tengo cuenta <a class="text-link" href="{% url 'usuarios:registro_usuario' %}" >Crear</a>.</div>
			</div><!--//auth-form-container-->	

		</div><!--//auth-body-->
  
{% endblock contenido %}

usuarios/templates/signup.html
{% extends "base_log_sign.html" %}
{% load static %}

{% block titulo %}
<title>Registro</title>
{% endblock titulo %}

{% block contenido %}

{% if form.errors %}
<div class="alert alert-warning">
	<p>Error de registro</p>
</div>
{% endif %}  
<body class="app app-signup p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon mr-2" src="{% static 'images/app-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-4">Registro de Usuario</h2>					
	
					<div class="auth-form-container text-left mx-auto">
						<form class="auth-form auth-signup-form" method="POST">
                            {% csrf_token %}         
							<div class="mb-3">
								<label class="sr-only" for="id_username">Nombre de Usuario</label>
								<input id="id_username" name="username" type="text" class="form-control signup-name" placeholder="Usuario" required="required">
							</div>
							<div class="email mb-3">
								<label class="sr-only" for="id_username">Email</label>
								<input id="id_email" name="email" type="text" class="form-control signup-email" placeholder="Email" required="required">
							</div>
							<div class="password mb-3">
								<label class="sr-only" for="id_password">Contraseña</label>
								<input id="id_password" name="password" type="password" class="form-control signup-password" placeholder="Contraseña" required="required">
							</div>
                            <div class=" mb-3">
                                <label class="" for="id_estado">Estado</label>
								{{form.estado}}
							</div>
                            <div class=" mb-3">
                                <label class="" for="id_municipio">Municipio</label>
								{{form.municipio}}
							</div>
							<div class="extra mb-3">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
									<label class="form-check-label" for="RememberPassword">
									Acepto las <a href="#" class="app-link">Condiciones de servicio</a> y <a href="#" class="app-link">Politicas de Privacidad</a>.
									</label>
								</div>
							</div><!--//extra-->
							
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">Registrarme</button>
							</div>
						</form><!--//auth-form-->
						
						<div class="auth-option text-center pt-5">Ya tengo una cuenta <a class="text-link" href="{% url 'usuarios:login_usuario' %}" >Log in</a></div>
					</div><!--//auth-form-container-->	
					
					
				    
			    </div><!--//auth-body-->
  
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/funciones.js' %}"></script>
{% endblock js %}