usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('lista/', views.UsuarioList.as_view(), name='lista_usuario'),
    path('lista-pdf/', views.UsuarioListPdf.as_view(), name='lista_pdf_usuario'),
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo_usuario'),
    path('municipios/', views.obtiene_municipios, name='obtiene_municipios'),
    path('activar/<slug:uid64>/<slug:token>', views.ActivarCuenta.as_view(), name='activar_cuenta'),
    path('eliminar/<int:pk>', views.UsuarioEliminar.as_view(), name='eliminar_usuario'),
    path('editar/<int:pk>', views.UsuarioActualizar.as_view(), name='editar_usuario'),
    path('detalles/<int:pk>', views.UsuarioDetalle.as_view(), name='detalles_usuario'),
    path('login/', views.UsuarioLogin.as_view(), name='login_usuario'),
    path('registro/', views.UsuarioRegistro.as_view(), name='registro_usuario'),
    path('dar-usuario/<int:pk>', views.UsuarioDarUsuario, name='dar_usuario_usuario'),
    path('dar-administrador/<int:pk>', views.UsuarioDarAdministrador, name='dar_administrador_usuario'),
    path('modificar-grupo/<int:user_id>/<int:grupo_id>/<int:opcion>', views.UsuarioModificarGrupo, name='modificar_grupo_usuario'),
    path("logout/", LogoutView.as_view(), name="logout"),
]

videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from videojuego.views import VideojuegoViewSet, CategoriaViewSet

router = routers.DefaultRouter()
router.register(r'videojuegos-api', VideojuegoViewSet)
router.register(r'categorias-api', CategoriaViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videojuegos/', include('videojuego.urls_videojuego')),
    path('categorias/', include('videojuego.urls_categoria')),
    path('usuarios/', include('usuarios.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User

# Create your models here.

class Usuario(User):
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado", on_delete=models.CASCADE)
    municipio = models.ForeignKey("usuarios.Municipio", verbose_name="Municipio", on_delete=models.CASCADE)
    foto = models.ImageField("Foto de perfil", upload_to='perfiles', blank=True, null=True)
    
    class Meta:
        permissions = [('permiso_usuario','usuario')]


class Estado(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Municipio(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.ForeignKey("usuarios.Estado", verbose_name="Estado", on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    

usuarios/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Usuario

        fields = ('first_name','username','password','email','estado','municipio','foto')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Contraseña'}),
            'estado':forms.Select(attrs={'class':'form-control'}),
            'municipio':forms.Select(attrs={'class':'form-control'}),
            'foto':forms.FileInput(attrs={'class':'form-control'})
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class UsuarioActualizarForm(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('first_name','username','email','estado','municipio','foto')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'estado':forms.Select(attrs={'class':'form-control'}),
            'municipio':forms.Select(attrs={'class':'form-control'}),
            'foto':forms.FileInput(attrs={'class':'form-control'})
        }

class UsuarioRegistroForm(forms.ModelForm):

    class Meta:
        model = Usuario
        
        fields = ('username','password','email','estado','municipio')

        widgets = {
            'estado':forms.Select(attrs={'class':'form-control'}),
            'municipio':forms.Select(attrs={'class':'form-control'}),
        }

    def save(self, commit=True):
        user = super(UsuarioRegistroForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuarios/views.py
import functools

from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from .token import token_activacion
from django.views.generic import ListView
from .models import Usuario, Estado, Municipio
from .forms import UsuarioForm, UsuarioRegistroForm, UsuarioActualizarForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.mail import EmailMessage
from django.views.generic import TemplateView
from django.contrib import messages
from django_weasyprint import WeasyTemplateResponseMixin
from django_weasyprint.views import CONTENT_TYPE_PNG, WeasyTemplateResponse
from django.conf import settings
from django.contrib.auth.models import Group
from django import template

class NuevoUsuario(CreateView):
    model = Usuario
    form_class = UsuarioForm
    extra_context = {'etiqueta':'Nuevo','boton':'Agregar'}
    success_url = reverse_lazy('usuarios:lista_usuario')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.save()
        grupo = Group.objects.get(name='usuario') 
        user.groups.add(grupo)
        return super().form_valid(form)

class UsuarioRegistro(CreateView):
    template_name = 'signup.html'
    model = Usuario
    form_class = UsuarioRegistroForm
    success_url = reverse_lazy('usuarios:login_usuario')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        grupo = Group.objects.get(name='usuario') 
        user.groups.add(grupo)

        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        mensaje = render_to_string('confirmar_cuenta.html',
            {
                'usuario': user,
                'dominio': dominio,
                'uid': uid,
                'token': token
            }
        )
        asunto = 'Activa Cuenta Videojuegos'
        to = user.email
        email = EmailMessage(
            asunto,
            mensaje,
            to = [to]
        )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)

class ActivarCuenta(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uid64'])
            token = kwargs['token']
            user = Usuario.objects.get(id=uid)
        except:
            user = None
        
        if user and token_activacion.check_token(user,token):
            user.is_active = True
            user.save()
            messages.success(self.request, 'Cuenta activada con éxito.')
        else:
            messages.error(self.request, 'Token invalido, contacta al administrador')
        
        return redirect('usuarios:login_usuario')

def obtiene_municipios(request):
    if request.method == 'GET':
        return JsonResponse({'error':'Peticion incorrecta'}, safe=False, status=403)
    id_estado = request.POST.get('id')
    municipios = Municipio.objects.filter(estado_id=id_estado)

    json = []
    if not municipios:
        json.append({'error':'No se encontraron municipios para ese estado'})
    
    for municipio in municipios:
        json.append({'id':municipio.id, 'nombre':municipio.nombre})

    return JsonResponse(json, safe=False)

class UsuarioList(ListView):
    model = Usuario
    # usuario = Group.objects.get(name='usuario')
    # administrador = Group.objects.get(name='administrador')
    grupos = Group.objects.all()
    # extra_context = {'usuario_grupo':usuario, 'admin_grupo':administrador}
    extra_context = {'grupos':grupos}

class UsuarioEliminar(DeleteView):
    model = Usuario
    success_url = reverse_lazy('usuarios:lista_usuario')

class UsuarioActualizar(UpdateView):
    model = Usuario
    form_class = UsuarioActualizarForm
    extra_context = {'etiqueta':'Editar','boton':'Guardar'}
    success_url = reverse_lazy('usuarios:lista_usuario')

class UsuarioDetalle(DetailView):
    model = Usuario

class UsuarioLogin(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    
    def get_success_url(self):
        self.request.session['cuantos'] = 0
        self.request.session['total'] = 0.0
        self.request.session['videojuegos'] = {}
        return super().get_success_url()

def UsuarioDarUsuario(request,pk):
    usuario = Usuario.objects.get(id=pk)
    grupo = Group.objects.get(name='usuario') 
    usuario.groups.add(grupo)
    return redirect('usuarios:lista_usuario')

def UsuarioDarAdministrador(request,pk):
    usuario = Usuario.objects.get(id=pk)
    grupo = Group.objects.get(name='administrador') 
    usuario.groups.add(grupo)
    return redirect('usuarios:lista_usuario')

def UsuarioModificarGrupo(request, user_id, grupo_id, opcion):
    grupo = Group.objects.get(id=grupo_id)
    usuario = Usuario.objects.get(id=user_id)
    if opcion == 0:
        if grupo not in usuario.groups.all():
            messages.error(request, f'El usuario {usuario.username} no pertenece al grupo {grupo.name}.')
        else:
            if usuario.groups.count() <= 1:
                messages.error(request, f'El usuario {usuario.username} no puede quedar sin un grupo.')
            else:
                usuario.groups.remove(grupo)
                messages.success(request, f'El usuario {usuario.username} ya no pertenece al grupo {grupo.name}.')
    elif opcion == 1:
        if grupo in usuario.groups.all():
            messages.error(request, f'El usuario {usuario.username} ya pertenece al grupo {grupo.name}.')
        else:
            usuario.groups.add(grupo)
            messages.success(request, f'El usuario {usuario.username} pertenece al grupo {grupo.name}.')

    return redirect('usuarios:lista_usuario')

class VistaPdf(ListView):
    model = Usuario
    template_name = 'usuarios/usuario_pdf.html'

class UsuarioListPdf(WeasyTemplateResponseMixin, VistaPdf):
    # output of MyModelView rendered as PDF with hardcoded CSS
    pdf_stylesheets = [
        settings.STATICFILES_DIRS[0] + '/css/portal.css',
        settings.STATICFILES_DIRS[0] + '/css/estilos.css',
    ]
    # show pdf in-line (default: True, show download dialog)
    pdf_attachment = False
    # custom response class to configure url-fetcher
    pdf_name = 'foo.pdf'

usuarios/templates/usuarios/usuario_detail.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    Detalles Videojuego
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">Detalle Usuario</h1>
    <div class="card d-inline-flex">
        
        {% if usuario.foto %}
            <img class="card-img-top rounded" style="width: 300px"  src="{{ MEDIA_URL }}{{usuario.foto}}" alt="Fotografia">
            {% else %}
            <img class="card-img-top rounded" style="width: 300px"  src="{% static 'images/user_profile_default.jpg' %}" alt="Fotografia">
        {% endif %}
        <div class="card-body">
            <h4 class="card-title">{{usuario.username}}</h1>
            <p>{{usuario.first_name}}<br>
                {{usuario.estado}}<br>
                {{usuario.municipio}}<br>
            </p>
        </div>
    </div>
{% endblock contenido %}

usuarios/templates/usuarios/usuario_form.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    {{etiqueta}} Usuario
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">{{etiqueta}} Usuario</h1>
    <div class="card  p-2">
        <div class="card-body">
            <div class="mb-3 row">
                <div class="form-group">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-secondary">{{boton}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/funciones.js' %}"></script>
{% endblock js %}

usuarios/templates/usuarios/usuario_list.html
{% extends "base2.html" %}
{% load static %}

{% block titulo %}
    Lista de Usuarios
{% endblock titulo %}

{% block contenido %}
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}success{% endif %}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
        

    <h1 class="app-page-title">Usuarios</h1>
    <div class="card">
        <div class="card-body">
                <table class="table">
                    <thead>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Nombre de Usuario</th>
                        <th>Estado</th>
                        <th>Municipio</th>
                        <th>Acciones</th>
                        {% for grupo in grupos %}
                            <th>{{grupo}}</th>
                        {% endfor %}
                    </thead>
                    <tbody>
                        {% for usuario in object_list %}
                        <tr>
                            <td>{{usuario.id}}</td>
                            <td>{{usuario.first_name}}</td>
                            <td>{{usuario.username}}</td>
                            <td>{{usuario.estado}}</td>
                            <td>{{usuario.municipio}}</td>
                            <td>
                                <a href="{% url 'usuarios:detalles_usuario' usuario.id %}">Detalles</a>
                                <a href="{% url 'usuarios:editar_usuario' usuario.id %}">Editar</a>
                                <button onclick="muestra_modal('{% url 'usuarios:eliminar_usuario' usuario.id %}', '{{usuario.username}}')" type="button" class="btn btn-primary delete_example" data-toggle="modal" data-target="#exampleModal">
                                    Eliminar
                                </button>
                            </td>
                            {% for grupo in grupos %}
                                <td>
                                    <a href="{% url 'usuarios:modificar_grupo_usuario' usuario.id grupo.id 1 %}">
                                        <button class="btn btn-primary {% if grupo in usuario.groups.all %}disabled{% endif %}" type="button"  >Dar</button>
                                    </a>
                                    <a href="{% url 'usuarios:modificar_grupo_usuario' usuario.id grupo.id 0 %}">
                                        <button class="btn btn-primary {% if grupo in usuario.groups.all %}{% else %}disabled{% endif %}" type="button">Quitar</button>
                                    </a>
                                </td>
                            {% endfor %}
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'usuarios:lista_pdf_usuario' %}" target="_blank">
                    <button type="button" class="btn btn-primary">Imprimir</button>
                </a>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar Videojuego</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body" id="modal-cuerpo">
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form id="formEliminar" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary save_changes">Aceptar</button>
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/funciones.js'%}"></script>
{% endblock js %}

usuarios/templates/usuarios/usuario_pdf.html
<h1 class="app-page-title">Usuarios</h1>
<table class="table">
    <thead>
        <th>ID</th>
        <th>Nombre</th>
        <th>Nombre de Usuario</th>
        <th>Estado</th>
        <th>Municipio</th>
    </thead>
    <tbody>
        {% for usuario in object_list %}
        <tr>
            <td>{{usuario.id}}</td>
            <td>{{usuario.first_name}}</td>
            <td>{{usuario.username}}</td>
            <td>{{usuario.estado}}</td>
            <td>{{usuario.municipio}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>